/* Generated By:JavaCC: Do not edit this line. ASTS_DConstants.java */
package c_ast_descendente;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ASTS_DConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digitoPositivo = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int parteEntera = 4;
  /** RegularExpression Id. */
  int parteDecimal = 5;
  /** RegularExpression Id. */
  int decimal = 6;
  /** RegularExpression Id. */
  int exponencial = 7;
  /** RegularExpression Id. */
  int and = 8;
  /** RegularExpression Id. */
  int or = 9;
  /** RegularExpression Id. */
  int not = 10;
  /** RegularExpression Id. */
  int ent = 11;
  /** RegularExpression Id. */
  int real = 12;
  /** RegularExpression Id. */
  int bool = 13;
  /** RegularExpression Id. */
  int string = 14;
  /** RegularExpression Id. */
  int nulo = 15;
  /** RegularExpression Id. */
  int falso = 16;
  /** RegularExpression Id. */
  int verdadero = 17;
  /** RegularExpression Id. */
  int proc = 18;
  /** RegularExpression Id. */
  int If = 19;
  /** RegularExpression Id. */
  int Else = 20;
  /** RegularExpression Id. */
  int While = 21;
  /** RegularExpression Id. */
  int struct = 22;
  /** RegularExpression Id. */
  int New = 23;
  /** RegularExpression Id. */
  int Delete = 24;
  /** RegularExpression Id. */
  int read = 25;
  /** RegularExpression Id. */
  int write = 26;
  /** RegularExpression Id. */
  int nl = 27;
  /** RegularExpression Id. */
  int type = 28;
  /** RegularExpression Id. */
  int call = 29;
  /** RegularExpression Id. */
  int identificador = 30;
  /** RegularExpression Id. */
  int literal_entero = 31;
  /** RegularExpression Id. */
  int literal_cadena = 32;
  /** RegularExpression Id. */
  int literal_real = 33;
  /** RegularExpression Id. */
  int menorIgual = 34;
  /** RegularExpression Id. */
  int mayorIgual = 35;
  /** RegularExpression Id. */
  int igualdad = 36;
  /** RegularExpression Id. */
  int distinto = 37;
  /** RegularExpression Id. */
  int cambioSec = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<decimal>",
    "<exponencial>",
    "<and>",
    "<or>",
    "<not>",
    "<ent>",
    "<real>",
    "<bool>",
    "<string>",
    "<nulo>",
    "<falso>",
    "<verdadero>",
    "<proc>",
    "<If>",
    "<Else>",
    "<While>",
    "<struct>",
    "<New>",
    "<Delete>",
    "<read>",
    "<write>",
    "<nl>",
    "<type>",
    "<call>",
    "<identificador>",
    "<literal_entero>",
    "<literal_cadena>",
    "<literal_real>",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "<token of kind 39>",
    "<token of kind 40>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"^\"",
    "\"@\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\".\"",
    "\">\"",
    "\"<\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
