package model.lexico;

public enum ClaseLexica {
    INT, REAL, BOOL, STRING, AND, OR, NOT, NULL, TRUE, FALSE, PROC, IF, ELSE, WHILE, STRUCT,
    NEW, DELETE, READ, WRITE, NL, TYPE, CALL, MAS, MENOS, MUL, DIV, MOD, MENOR, MAYOR, MENOREQ,
    MAYOREQ, IGUAL, DIST, ASIG, PARAP, PARCIE, PUNYCOMA, CORAP, CORCIE, PUNTO, PUNTERO, COMA,
    LLAVAP, LLAVCIE, REFE, CAMBSEC, EVAL, ID, LITENT, LITREAL, LITCAD, EOF, ERROR
}