package model.lexico;

public enum ClaseLexica {
	MAS, MENOS, MUL, DIV, MENOR, MAYOR, MENOREQ, MAYOREQ, IGUAL, DIST, ASIG, 
	PARAP, PARCIE, PUNYCOMA, COMA, LLAVAP, LLAVCIE, CAMBIOSEC, EVAL, ID, INT, REAL, BOOL,
	TRUE, FALSE, AND, OR, NOT, EOF, ENT, PUNTO, ERROR
}
